// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atgqhelwpdiksrhvxbnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0Z3FoZWx3cGRpa3NyaHZ4Ym5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyOTQ1ODIsImV4cCI6MjA2NDg3MDU4Mn0.K3KAwpx3G9ejgv5mw3IgFqo85cqFrAAQ8zq-kgnTadM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);